language: go
go:
    - 1.7
#   - tip
before_script:
    - go vet ./...
before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/axw/gocov/gocov
    - go get github.com/modocache/gover
    - go get github.com/mattn/goveralls
script:
    - go test -coverprofile=datastore.coverprofile ./datastore
    - go test -coverprofile=blenc.coverprofile ./blenc
    - go test -coverprofile=graph.coverprofile ./graph
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
    - bash <(curl -s https://codecov.io/bash) -f gover.coverprofile
