// Code generated by "stringer -type=beDirNodeState -output blenc_bedirnodestate.generated.go"; DO NOT EDIT

package graph

import "fmt"

const _beDirNodeState_name = "beDirNodeStateUnloadedbeDirNodeStateLoadingbeDirNodeStateIdlebeDirNodeStateSaveRequestedbeDirNodeStateSavingbeDirNodeStateLoadError"

var _beDirNodeState_index = [...]uint8{0, 22, 43, 61, 88, 108, 131}

func (i beDirNodeState) String() string {
	if i < 0 || i >= beDirNodeState(len(_beDirNodeState_index)-1) {
		return fmt.Sprintf("beDirNodeState(%d)", i)
	}
	return _beDirNodeState_name[_beDirNodeState_index[i]:_beDirNodeState_index[i+1]]
}
