permissions:
  contents: read
name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: golangci-lint
        run: |
          go tool golangci-lint run --timeout 5m
