name: Tests
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        go-version:
          - "1.17"
          - "1.18"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go vet ./...
      - if: ${{ runner.os == 'Windows' }}
        run: go get .cov
      - run: go test -v -coverprofile=profile.cov ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
